const types = {
  TEMPLATES_BEGIN: "TEMPLATES_BEGIN",
  TEMPLATES_SUCCESS: "TEMPLATES_SUCCESS",
  TEMPLATES_ERR: "TEMPLATES_ERR",
  INIT_TEMPLATES_RENDER: "INIT_TEMPLATES_RENDER",
  TEMPLATES_SEARCH_BEGIN: "TEMPLATES_SEARCH_BEGIN",
  TEMPLATES_SEARCH: "TEMPLATES_SEARCH",
  TEMPLATES_SEARCH_CLEAR: "TEMPLATES_SEARCH_CLEAR",
  FILTER_BY_CATEGORY_BEGIN: "FILTER_BY_CATEGORY_BEGIN",
  FILTER_BY_CATEGORY: "FILTER_BY_CATEGORY",
  FILTER_BY_CATEGORY_CLEAR: "FILTER_BY_CATEGORY_CLEAR",
  SORT_BY_NAME_BEGIN: "SORT_BY_NAME_BEGIN",
  SORT_BY_NAME: "SORT_BY_NAME",
  SORT_BY_NAME_CLEAR: "SORT_BY_NAME_CLEAR",
  SORT_BY_DATE_BEGIN: "SORT_BY_DATE_BEGIN",
  SORT_BY_DATE: "SORT_BY_DATE",
  SORT_BY_DATE_CLEAR: "SORT_BY_DATE_CLEAR",
};

export default types;
