const types = {
  TEMPLATES_BEGIN: "TEMPLATES_BEGIN",
  TEMPLATES_SUCCESS: "TEMPLATES_SUCCESS",
  TEMPLATES_ERR: "TEMPLATES_ERR",
  TEMPLATES_INIT_FILTER: "TEMPLATES_INIT_FILTER",
  TEMPLATES_SEARCH_BEGIN: "TEMPLATES_SEARCH_BEGIN",
  TEMPLATES_SEARCH: "TEMPLATES_SEARCH",
  TEMPLATES_SEARCH_CLEAR: "TEMPLATES_SEARCH_CLEAR",
};

export default types;
